// 置顶音效
const order = [
  'glockenspiel', 'celesta', 'tinkle_bell', 'tubular_bells',
  'taiko_drum', 'synth_drum', 'timpani',
  'fx_3_crystal', 'pad_6_metallic', 'lead_5_charang'
];

export const INSTRUMENTS: { name: string; label: string }[] = [
  { name: "accordion", label: "手风琴" },
  { name: "acoustic_bass", label: "原声贝斯" },
  { name: "acoustic_grand_piano", label: "大钢琴" },
  { name: "acoustic_guitar_nylon", label: "尼龙吉他" },
  { name: "acoustic_guitar_steel", label: "钢弦吉他" },
  { name: "agogo", label: "阿哥哥铃" },
  { name: "alto_sax", label: "中音萨克斯" },
  { name: "applause", label: "掌声" },
  { name: "bagpipe", label: "风笛" },
  { name: "banjo", label: "班卓琴" },
  { name: "baritone_sax", label: "上低音萨克斯" },
  { name: "bassoon", label: "巴松" },
  { name: "bird_tweet", label: "鸟叫" },
  { name: "blown_bottle", label: "吹瓶子" },
  { name: "brass_section", label: "铜管组" },
  { name: "breath_noise", label: "呼吸声" },
  { name: "bright_acoustic_piano", label: "明亮钢琴" },
  { name: "celesta", label: "钢片琴" },
  { name: "cello", label: "大提琴" },
  { name: "choir_aahs", label: "合唱“啊”" },
  { name: "church_organ", label: "教堂风琴" },
  { name: "clarinet", label: "单簧管" },
  { name: "clavinet", label: "键式拨弦琴" },
  { name: "contrabass", label: "低音提琴" },
  { name: "distortion_guitar", label: "失真吉他" },
  { name: "drawbar_organ", label: "拉杆风琴" },
  { name: "dulcimer", label: "洋琴" },
  { name: "electric_bass_finger", label: "电贝斯（手弹）" },
  { name: "electric_bass_pick", label: "电贝斯（拨片）" },
  { name: "electric_grand_piano", label: "电动大钢琴" },
  { name: "electric_guitar_clean", label: "清音电吉他" },
  { name: "electric_guitar_jazz", label: "爵士电吉他" },
  { name: "electric_guitar_muted", label: "闷音电吉他" },
  { name: "electric_piano_1", label: "电钢琴1" },
  { name: "electric_piano_2", label: "电钢琴2" },
  { name: "english_horn", label: "英国管" },
  { name: "fiddle", label: "乡村小提琴" },
  { name: "flute", label: "长笛" },
  { name: "french_horn", label: "圆号" },
  { name: "fretless_bass", label: "无品贝斯" },
  { name: "fx_1_rain", label: "雨声" },
  { name: "fx_2_soundtrack", label: "原声带" },
  { name: "fx_3_crystal", label: "水晶" },
  { name: "fx_4_atmosphere", label: "氛围" },
  { name: "fx_5_brightness", label: "明亮感" },
  { name: "fx_6_goblins", label: "哥布林" },
  { name: "fx_7_echoes", label: "回声" },
  { name: "fx_8_scifi", label: "科幻" },
  { name: "glockenspiel", label: "钟琴" },
  { name: "guitar_fret_noise", label: "吉他滑弦" },
  { name: "guitar_harmonics", label: "吉他泛音" },
  { name: "gunshot", label: "枪声" },
  { name: "harmonica", label: "口琴" },
  { name: "harpsichord", label: "羽管键琴" },
  { name: "helicopter", label: "直升机" },
  { name: "honkytonk_piano", label: "酒吧钢琴" },
  { name: "kalimba", label: "拇指琴" },
  { name: "koto", label: "筝" },
  { name: "lead_1_square", label: "方波Lead" },
  { name: "lead_2_sawtooth", label: "锯齿波Lead" },
  { name: "lead_3_calliope", label: "管风笛Lead" },
  { name: "lead_4_chiff", label: "气息Lead" },
  { name: "lead_5_charang", label: "杂音Lead" },
  { name: "lead_6_voice", label: "人声Lead" },
  { name: "lead_7_fifths", label: "五度Lead" },
  { name: "lead_8_bass__lead", label: "低音Lead" },
  { name: "marimba", label: "马林巴" },
  { name: "melodic_tom", label: "旋律桶鼓" },
  { name: "music_box", label: "音乐盒" },
  { name: "muted_trumpet", label: "闷音小号" },
  { name: "oboe", label: "双簧管" },
  { name: "ocarina", label: "陶笛" },
  { name: "orchestra_hit", label: "交响敲击" },
  { name: "orchestral_harp", label: "竖琴" },
  { name: "overdriven_guitar", label: "过载吉他" },
  { name: "pad_1_new_age", label: "新时代Pad" },
  { name: "pad_2_warm", label: "温暖Pad" },
  { name: "pad_3_polysynth", label: "合成Pad" },
  { name: "pad_4_choir", label: "人声Pad" },
  { name: "pad_5_bowed", label: "拉奏Pad" },
  { name: "pad_6_metallic", label: "金属Pad" },
  { name: "pad_7_halo", label: "光环Pad" },
  { name: "pad_8_sweep", label: "扫弦Pad" },
  { name: "pan_flute", label: "排箫" },
  { name: "percussive_organ", label: "打击风琴" },
  { name: "piccolo", label: "短笛" },
  { name: "pizzicato_strings", label: "拨奏弦乐" },
  { name: "recorder", label: "竖笛" },
  { name: "reed_organ", label: "簧管风琴" },
  { name: "reverse_cymbal", label: "倒钹声" },
  { name: "rock_organ", label: "摇滚风琴" },
  { name: "seashore", label: "海浪声" },
  { name: "shakuhachi", label: "尺八" },
  { name: "shamisen", label: "三味线" },
  { name: "shanai", label: "沙奈笛" },
  { name: "sitar", label: "锡塔尔琴" },
  { name: "slap_bass_1", label: "拍奏贝斯1" },
  { name: "slap_bass_2", label: "拍奏贝斯2" },
  { name: "soprano_sax", label: "高音萨克斯" },
  { name: "steel_drums", label: "钢鼓" },
  { name: "string_ensemble_1", label: "弦乐合奏1" },
  { name: "string_ensemble_2", label: "弦乐合奏2" },
  { name: "synth_bass_1", label: "合成贝斯1" },
  { name: "synth_bass_2", label: "合成贝斯2" },
  { name: "synth_brass_1", label: "合成铜管1" },
  { name: "synth_brass_2", label: "合成铜管2" },
  { name: "synth_choir", label: "合成人声" },
  { name: "synth_drum", label: "电子鼓" },
  { name: "synth_strings_1", label: "合成弦乐1" },
  { name: "synth_strings_2", label: "合成弦乐2" },
  { name: "taiko_drum", label: "太鼓" },
  { name: "tango_accordion", label: "探戈手风琴" },
  { name: "telephone_ring", label: "电话铃声" },
  { name: "tenor_sax", label: "次中音萨克斯" },
  { name: "timpani", label: "定音鼓" },
  { name: "tinkle_bell", label: "小铃铛" },
  { name: "tremolo_strings", label: "抖弓弦乐" },
  { name: "trombone", label: "长号" },
  { name: "trumpet", label: "小号" },
  { name: "tuba", label: "大号" },
  { name: "tubular_bells", label: "管钟" },
  { name: "vibraphone", label: "颤音琴" },
  { name: "viola", label: "中提琴" },
  { name: "violin", label: "小提琴" },
  { name: "voice_oohs", label: "人声“呜”" },
  { name: "whistle", label: "口哨" },
  { name: "woodblock", label: "木鱼" },
  { name: "xylophone", label: "木琴" },
].sort((x, y) => {
  const ix = order.indexOf(x.name);
  const iy = order.indexOf(y.name);

  // 都在 order 中，按索引排序
  if (ix !== -1 && iy !== -1) return ix - iy;

  // x 在 order 中，y 不在
  if (ix !== -1) return -1;

  // y 在 order 中，x 不在
  if (iy !== -1) return 1;

  // 都不在 order 中，保持原顺序或其他逻辑
  return 0;
})
